name: Docker Build and Push

on:
  push:
    branches:
      - main  # 根据你的主分支名称调整（可能是 master）
  workflow_dispatch:
    inputs:
      custom_tag:
        description: '自定义镜像标签 (留空则使用默认)'
        required: false
        default: 'manual'
      skip_push:
        description: '跳过推送镜像'
        required: false
        default: 'false'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/yeisme0.xyz:latest
            ghcr.io/${{ github.repository_owner }}/yeisme0.xyz:${{ github.sha }}
